### ISSUE TITLE
iApp too big for Heat DB

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-heat-plugins#52]
Hi

When creating the following resource using the full_template property

```
type: F5::Sys::iAppTemplate
depends_on: [bigip_rsrc, partition]
properties:
  name:  { get_param: iapp_template_name }
  bigip_server: { get_resource: bigip_rsrc }
  partition: { get_resource: partition }
  full_template: { get_file: cloudband.dns.iapp }
```

It fails in the UIs with the following message

Resource CREATE failed: NonextantTemplateNameException: resources.iapp_template: Template name not found.

Looking in the heat-engine.log file it seems this turns out to be that the iApp template is too big for the column in the database:

2016-04-15 09:19:34.357 11388 ERROR oslo_db.sqlalchemy.exc_filters DataError: (1406, "Data too long for column 'resource_properties' at row 1")

I attach a file with the full heat-engine.log

Thanks

```
  Ulises
```

[heat-engine.log.txt](https://github.com/F5Networks/f5-openstack-heat-plugins/files/220694/heat-engine.log.txt)
